/**
 * This class is generated by jOOQ
 */
package net.cworks.wowreg.domain;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttendeeMeta implements java.io.Serializable {

	private static final long serialVersionUID = -1922080388;

	private java.lang.Integer  id;
	private java.lang.Integer  attendeeId;
	private java.lang.String   metaKey;
	private java.lang.String   metaValue;
	private java.lang.String   metaType;
	private java.sql.Timestamp dateAdded;

	public AttendeeMeta() {}

	public AttendeeMeta(
		java.lang.Integer  id,
		java.lang.Integer  attendeeId,
		java.lang.String   metaKey,
		java.lang.String   metaValue,
		java.lang.String   metaType,
		java.sql.Timestamp dateAdded
	) {
		this.id = id;
		this.attendeeId = attendeeId;
		this.metaKey = metaKey;
		this.metaValue = metaValue;
		this.metaType = metaType;
		this.dateAdded = dateAdded;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getAttendeeId() {
		return this.attendeeId;
	}

	public void setAttendeeId(java.lang.Integer attendeeId) {
		this.attendeeId = attendeeId;
	}

	public java.lang.String getMetaKey() {
		return this.metaKey;
	}

	public void setMetaKey(java.lang.String metaKey) {
		this.metaKey = metaKey;
	}

	public java.lang.String getMetaValue() {
		return this.metaValue;
	}

	public void setMetaValue(java.lang.String metaValue) {
		this.metaValue = metaValue;
	}

	public java.lang.String getMetaType() {
		return this.metaType;
	}

	public void setMetaType(java.lang.String metaType) {
		this.metaType = metaType;
	}

	public java.sql.Timestamp getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(java.sql.Timestamp dateAdded) {
		this.dateAdded = dateAdded;
	}
}
