/**
 * This class is generated by jOOQ
 */
package net.cworks.wowreg.domain;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttendeeCost implements java.io.Serializable {

	private static final long serialVersionUID = -939925642;

	private java.lang.Integer id;
	private java.lang.Integer attendeeId;
	private java.lang.String  shirtSize;
	private java.lang.Integer shirtCost;
	private java.lang.Integer roomCost;
	private java.lang.Integer donationCost;
	private java.lang.String  ageClass;
	private java.lang.Integer totalCost;

	public AttendeeCost() {}

	public AttendeeCost(
		java.lang.Integer id,
		java.lang.Integer attendeeId,
		java.lang.String  shirtSize,
		java.lang.Integer shirtCost,
		java.lang.Integer roomCost,
		java.lang.Integer donationCost,
		java.lang.String  ageClass,
		java.lang.Integer totalCost
	) {
		this.id = id;
		this.attendeeId = attendeeId;
		this.shirtSize = shirtSize;
		this.shirtCost = shirtCost;
		this.roomCost = roomCost;
		this.donationCost = donationCost;
		this.ageClass = ageClass;
		this.totalCost = totalCost;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getAttendeeId() {
		return this.attendeeId;
	}

	public void setAttendeeId(java.lang.Integer attendeeId) {
		this.attendeeId = attendeeId;
	}

	public java.lang.String getShirtSize() {
		return this.shirtSize;
	}

	public void setShirtSize(java.lang.String shirtSize) {
		this.shirtSize = shirtSize;
	}

	public java.lang.Integer getShirtCost() {
		return this.shirtCost;
	}

	public void setShirtCost(java.lang.Integer shirtCost) {
		this.shirtCost = shirtCost;
	}

	public java.lang.Integer getRoomCost() {
		return this.roomCost;
	}

	public void setRoomCost(java.lang.Integer roomCost) {
		this.roomCost = roomCost;
	}

	public java.lang.Integer getDonationCost() {
		return this.donationCost;
	}

	public void setDonationCost(java.lang.Integer donationCost) {
		this.donationCost = donationCost;
	}

	public java.lang.String getAgeClass() {
		return this.ageClass;
	}

	public void setAgeClass(java.lang.String ageClass) {
		this.ageClass = ageClass;
	}

	public java.lang.Integer getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(java.lang.Integer totalCost) {
		this.totalCost = totalCost;
	}
}
