/**
 * This class is generated by jOOQ
 */
package net.cworks.wowreg.domain;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttendeeToAttendeeGroup implements java.io.Serializable {

	private static final long serialVersionUID = -1400877625;

	private java.lang.Integer id;
	private java.lang.Integer attendeeId;
	private java.lang.Integer groupId;

	public AttendeeToAttendeeGroup() {}

	public AttendeeToAttendeeGroup(
		java.lang.Integer id,
		java.lang.Integer attendeeId,
		java.lang.Integer groupId
	) {
		this.id = id;
		this.attendeeId = attendeeId;
		this.groupId = groupId;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getAttendeeId() {
		return this.attendeeId;
	}

	public void setAttendeeId(java.lang.Integer attendeeId) {
		this.attendeeId = attendeeId;
	}

	public java.lang.Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(java.lang.Integer groupId) {
		this.groupId = groupId;
	}
}
