/**
 * This class is generated by jOOQ
 */
package net.cworks.wowreg.domain;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttendeeGroup implements java.io.Serializable {

	private static final long serialVersionUID = -42315452;

	private java.lang.Integer id;
	private java.lang.Integer pocId;
	private java.lang.String  groupName;

	public AttendeeGroup() {}

	public AttendeeGroup(
		java.lang.Integer id,
		java.lang.Integer pocId,
		java.lang.String  groupName
	) {
		this.id = id;
		this.pocId = pocId;
		this.groupName = groupName;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getPocId() {
		return this.pocId;
	}

	public void setPocId(java.lang.Integer pocId) {
		this.pocId = pocId;
	}

	public java.lang.String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(java.lang.String groupName) {
		this.groupName = groupName;
	}
}
