/**
 * This class is generated by jOOQ
 */
package net.cworks.wowreg.domain;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Events implements java.io.Serializable {

	private static final long serialVersionUID = -699568326;

	private java.lang.Integer  id;
	private java.lang.String   eventName;
	private java.lang.String   eventDesc;
	private java.sql.Timestamp startDate;
	private java.sql.Timestamp endDate;
	private java.sql.Timestamp registrationStart;
	private java.sql.Timestamp registrationEnd;
	private java.lang.String   address;
	private java.lang.String   city;
	private java.lang.String   state;
	private java.lang.String   zip;
	private java.lang.String   country;
	private java.lang.String   email;
	private java.lang.String   phone;
	private java.lang.String   venueName;
	private java.lang.String   venueUrl;
	private java.lang.String   venuePhone;
	private java.lang.String   venueEmail;
	private java.lang.Integer  registrationLimit;

	public Events() {}

	public Events(
		java.lang.Integer  id,
		java.lang.String   eventName,
		java.lang.String   eventDesc,
		java.sql.Timestamp startDate,
		java.sql.Timestamp endDate,
		java.sql.Timestamp registrationStart,
		java.sql.Timestamp registrationEnd,
		java.lang.String   address,
		java.lang.String   city,
		java.lang.String   state,
		java.lang.String   zip,
		java.lang.String   country,
		java.lang.String   email,
		java.lang.String   phone,
		java.lang.String   venueName,
		java.lang.String   venueUrl,
		java.lang.String   venuePhone,
		java.lang.String   venueEmail,
		java.lang.Integer  registrationLimit
	) {
		this.id = id;
		this.eventName = eventName;
		this.eventDesc = eventDesc;
		this.startDate = startDate;
		this.endDate = endDate;
		this.registrationStart = registrationStart;
		this.registrationEnd = registrationEnd;
		this.address = address;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.country = country;
		this.email = email;
		this.phone = phone;
		this.venueName = venueName;
		this.venueUrl = venueUrl;
		this.venuePhone = venuePhone;
		this.venueEmail = venueEmail;
		this.registrationLimit = registrationLimit;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getEventName() {
		return this.eventName;
	}

	public void setEventName(java.lang.String eventName) {
		this.eventName = eventName;
	}

	public java.lang.String getEventDesc() {
		return this.eventDesc;
	}

	public void setEventDesc(java.lang.String eventDesc) {
		this.eventDesc = eventDesc;
	}

	public java.sql.Timestamp getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.sql.Timestamp startDate) {
		this.startDate = startDate;
	}

	public java.sql.Timestamp getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.sql.Timestamp endDate) {
		this.endDate = endDate;
	}

	public java.sql.Timestamp getRegistrationStart() {
		return this.registrationStart;
	}

	public void setRegistrationStart(java.sql.Timestamp registrationStart) {
		this.registrationStart = registrationStart;
	}

	public java.sql.Timestamp getRegistrationEnd() {
		return this.registrationEnd;
	}

	public void setRegistrationEnd(java.sql.Timestamp registrationEnd) {
		this.registrationEnd = registrationEnd;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getState() {
		return this.state;
	}

	public void setState(java.lang.String state) {
		this.state = state;
	}

	public java.lang.String getZip() {
		return this.zip;
	}

	public void setZip(java.lang.String zip) {
		this.zip = zip;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getVenueName() {
		return this.venueName;
	}

	public void setVenueName(java.lang.String venueName) {
		this.venueName = venueName;
	}

	public java.lang.String getVenueUrl() {
		return this.venueUrl;
	}

	public void setVenueUrl(java.lang.String venueUrl) {
		this.venueUrl = venueUrl;
	}

	public java.lang.String getVenuePhone() {
		return this.venuePhone;
	}

	public void setVenuePhone(java.lang.String venuePhone) {
		this.venuePhone = venuePhone;
	}

	public java.lang.String getVenueEmail() {
		return this.venueEmail;
	}

	public void setVenueEmail(java.lang.String venueEmail) {
		this.venueEmail = venueEmail;
	}

	public java.lang.Integer getRegistrationLimit() {
		return this.registrationLimit;
	}

	public void setRegistrationLimit(java.lang.Integer registrationLimit) {
		this.registrationLimit = registrationLimit;
	}
}
