/**
 * This class is generated by jOOQ
 */
package net.cworks.wowreg.domain;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventPrices implements java.io.Serializable {

	private static final long serialVersionUID = 440884581;

	private java.lang.Integer id;
	private java.lang.String  item;
	private java.lang.String  category;
	private java.lang.String  desc;
	private java.lang.Integer price;

	public EventPrices() {}

	public EventPrices(
		java.lang.Integer id,
		java.lang.String  item,
		java.lang.String  category,
		java.lang.String  desc,
		java.lang.Integer price
	) {
		this.id = id;
		this.item = item;
		this.category = category;
		this.desc = desc;
		this.price = price;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getItem() {
		return this.item;
	}

	public void setItem(java.lang.String item) {
		this.item = item;
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public java.lang.String getDesc() {
		return this.desc;
	}

	public void setDesc(java.lang.String desc) {
		this.desc = desc;
	}

	public java.lang.Integer getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Integer price) {
		this.price = price;
	}
}
