/**
 * This class is generated by jOOQ
 */
package net.cworks.wowreg.domain;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaypalPaymentTx implements java.io.Serializable {

	private static final long serialVersionUID = 853462688;

	private java.lang.Integer  id;
	private java.lang.String   paypalId;
	private java.lang.String   paypalPayerId;
	private java.lang.String   paypalPayerEmail;
	private java.lang.String   paypalPayerFirstname;
	private java.lang.String   paypalPayerLastname;
	private java.lang.Integer  paypalTxAmount;
	private java.lang.String   paypalTxId;
	private java.lang.String   paypalTxState;
	private java.lang.String   paypalTxSelfUrl;
	private java.lang.String   paypalTxRefundUrl;
	private java.lang.String   paypalTxParentPaymentUrl;
	private java.sql.Timestamp paypalCreateTime;
	private java.sql.Timestamp paypalUpdateTime;
	private java.sql.Timestamp dateAdded;

	public PaypalPaymentTx() {}

	public PaypalPaymentTx(
		java.lang.Integer  id,
		java.lang.String   paypalId,
		java.lang.String   paypalPayerId,
		java.lang.String   paypalPayerEmail,
		java.lang.String   paypalPayerFirstname,
		java.lang.String   paypalPayerLastname,
		java.lang.Integer  paypalTxAmount,
		java.lang.String   paypalTxId,
		java.lang.String   paypalTxState,
		java.lang.String   paypalTxSelfUrl,
		java.lang.String   paypalTxRefundUrl,
		java.lang.String   paypalTxParentPaymentUrl,
		java.sql.Timestamp paypalCreateTime,
		java.sql.Timestamp paypalUpdateTime,
		java.sql.Timestamp dateAdded
	) {
		this.id = id;
		this.paypalId = paypalId;
		this.paypalPayerId = paypalPayerId;
		this.paypalPayerEmail = paypalPayerEmail;
		this.paypalPayerFirstname = paypalPayerFirstname;
		this.paypalPayerLastname = paypalPayerLastname;
		this.paypalTxAmount = paypalTxAmount;
		this.paypalTxId = paypalTxId;
		this.paypalTxState = paypalTxState;
		this.paypalTxSelfUrl = paypalTxSelfUrl;
		this.paypalTxRefundUrl = paypalTxRefundUrl;
		this.paypalTxParentPaymentUrl = paypalTxParentPaymentUrl;
		this.paypalCreateTime = paypalCreateTime;
		this.paypalUpdateTime = paypalUpdateTime;
		this.dateAdded = dateAdded;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getPaypalId() {
		return this.paypalId;
	}

	public void setPaypalId(java.lang.String paypalId) {
		this.paypalId = paypalId;
	}

	public java.lang.String getPaypalPayerId() {
		return this.paypalPayerId;
	}

	public void setPaypalPayerId(java.lang.String paypalPayerId) {
		this.paypalPayerId = paypalPayerId;
	}

	public java.lang.String getPaypalPayerEmail() {
		return this.paypalPayerEmail;
	}

	public void setPaypalPayerEmail(java.lang.String paypalPayerEmail) {
		this.paypalPayerEmail = paypalPayerEmail;
	}

	public java.lang.String getPaypalPayerFirstname() {
		return this.paypalPayerFirstname;
	}

	public void setPaypalPayerFirstname(java.lang.String paypalPayerFirstname) {
		this.paypalPayerFirstname = paypalPayerFirstname;
	}

	public java.lang.String getPaypalPayerLastname() {
		return this.paypalPayerLastname;
	}

	public void setPaypalPayerLastname(java.lang.String paypalPayerLastname) {
		this.paypalPayerLastname = paypalPayerLastname;
	}

	public java.lang.Integer getPaypalTxAmount() {
		return this.paypalTxAmount;
	}

	public void setPaypalTxAmount(java.lang.Integer paypalTxAmount) {
		this.paypalTxAmount = paypalTxAmount;
	}

	public java.lang.String getPaypalTxId() {
		return this.paypalTxId;
	}

	public void setPaypalTxId(java.lang.String paypalTxId) {
		this.paypalTxId = paypalTxId;
	}

	public java.lang.String getPaypalTxState() {
		return this.paypalTxState;
	}

	public void setPaypalTxState(java.lang.String paypalTxState) {
		this.paypalTxState = paypalTxState;
	}

	public java.lang.String getPaypalTxSelfUrl() {
		return this.paypalTxSelfUrl;
	}

	public void setPaypalTxSelfUrl(java.lang.String paypalTxSelfUrl) {
		this.paypalTxSelfUrl = paypalTxSelfUrl;
	}

	public java.lang.String getPaypalTxRefundUrl() {
		return this.paypalTxRefundUrl;
	}

	public void setPaypalTxRefundUrl(java.lang.String paypalTxRefundUrl) {
		this.paypalTxRefundUrl = paypalTxRefundUrl;
	}

	public java.lang.String getPaypalTxParentPaymentUrl() {
		return this.paypalTxParentPaymentUrl;
	}

	public void setPaypalTxParentPaymentUrl(java.lang.String paypalTxParentPaymentUrl) {
		this.paypalTxParentPaymentUrl = paypalTxParentPaymentUrl;
	}

	public java.sql.Timestamp getPaypalCreateTime() {
		return this.paypalCreateTime;
	}

	public void setPaypalCreateTime(java.sql.Timestamp paypalCreateTime) {
		this.paypalCreateTime = paypalCreateTime;
	}

	public java.sql.Timestamp getPaypalUpdateTime() {
		return this.paypalUpdateTime;
	}

	public void setPaypalUpdateTime(java.sql.Timestamp paypalUpdateTime) {
		this.paypalUpdateTime = paypalUpdateTime;
	}

	public java.sql.Timestamp getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(java.sql.Timestamp dateAdded) {
		this.dateAdded = dateAdded;
	}
}
