/**
 * This class is generated by jOOQ
 */
package net.cworks.wowreg.domain;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaypalPaymentAuth implements java.io.Serializable {

	private static final long serialVersionUID = -2131528012;

	private java.lang.Integer  id;
	private java.lang.String   paypalToken;
	private java.lang.String   paypalPayerId;
	private java.sql.Timestamp dateAdded;

	public PaypalPaymentAuth() {}

	public PaypalPaymentAuth(
		java.lang.Integer  id,
		java.lang.String   paypalToken,
		java.lang.String   paypalPayerId,
		java.sql.Timestamp dateAdded
	) {
		this.id = id;
		this.paypalToken = paypalToken;
		this.paypalPayerId = paypalPayerId;
		this.dateAdded = dateAdded;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getPaypalToken() {
		return this.paypalToken;
	}

	public void setPaypalToken(java.lang.String paypalToken) {
		this.paypalToken = paypalToken;
	}

	public java.lang.String getPaypalPayerId() {
		return this.paypalPayerId;
	}

	public void setPaypalPayerId(java.lang.String paypalPayerId) {
		this.paypalPayerId = paypalPayerId;
	}

	public java.sql.Timestamp getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(java.sql.Timestamp dateAdded) {
		this.dateAdded = dateAdded;
	}
}
