/**
 * This class is generated by jOOQ
 */
package net.cworks.wowreg.domain;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Registered implements java.io.Serializable {

	private static final long serialVersionUID = -2142133195;

	private java.lang.Integer  id;
	private java.lang.Integer  attendeeId;
	private java.sql.Timestamp registeredDate;
	private java.lang.String   status;

	public Registered() {}

	public Registered(
		java.lang.Integer  id,
		java.lang.Integer  attendeeId,
		java.sql.Timestamp registeredDate,
		java.lang.String   status
	) {
		this.id = id;
		this.attendeeId = attendeeId;
		this.registeredDate = registeredDate;
		this.status = status;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getAttendeeId() {
		return this.attendeeId;
	}

	public void setAttendeeId(java.lang.Integer attendeeId) {
		this.attendeeId = attendeeId;
	}

	public java.sql.Timestamp getRegisteredDate() {
		return this.registeredDate;
	}

	public void setRegisteredDate(java.sql.Timestamp registeredDate) {
		this.registeredDate = registeredDate;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}
}
